services:
  - type: web
    name: secretar-ia
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: GMAIL_CREDENTIALS_JSON
        sync: false  # Debes agregar el valor manualmente desde el dashboard
      - key: GMAIL_TOKEN_JSON
        sync: false
      - key: WHATSAPP_ACCESS_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: WHATSAPP_VERIFY_TOKEN
        sync: false